# Generated by Django 5.1.1 on 2024-09-23 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_subscription_delete_weatherhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
